---
# GitHub Action for Level 1 auditing of CVEs
# It is triggered whenever the CVE Update GitHub Action completes

name: CVE Auditor
on:
  workflow_run:
    workflows:
      - "CVE Update"
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - name: check delta
        run: |
          pwd
          ls -al
          head ./cves/delta.json