---
# GitHub Action for Level 1 auditing of CVEs
# It is triggered whenever the CVE Update GitHub Action completes

name: CVE Auditor
on:
  workflow_run:
    workflows:
      - "CVE Update"
    types:
      - completed

jobs:
  audit-cves:
    name: Test Step
    environment: deployment
    runs-on: ubuntu-latest
    env:
      # GITHUB_URL_ROOT: https://raw.githubusercontent.com/CVEProject/cvelistV5/refs/heads/main
      # https://raw.githubusercontent.com/CVEProject/cvelistV5/refs/heads/main/.github/workflows/dist/sourcemap-register.cjs
      # https://github.com/CVEProject/cvelistV5/blob/main/cves/deltaLog.json
      CVE_DELTALOG_JSON: https://github.com/CVEProject/cvelistV5/blob/main/cves/deltaLog.json
      CVE_UTIL_ROOT: https://raw.githubusercontent.com/CVEProject/cvelistV5/refs/heads/main/.github/workflows/dist
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 1
      - name: Setup Node to specific version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: check delta
        run: |
          pwd
          ls -al
          ls -al .github/workflows/dist
          mkdir -p .github/workflows/dist
          curl -L -o .github/workflows/dist/sourcemap-register.cjs ${CVE_UTIL_ROOT}/sourcemap-register.cjs
          curl -L -o .github/workflows/dist/index.mjs ${CVE_UTIL_ROOT}/index.js
          curl -L -o ./delta.json ${CVE_DELTALOG_JSON}
          ls -al
          head ./delta.json
          node ./.github/workflows/dist/index.js --version
