---
name: Auditor

on:
  workflow_run:
    workflows:
      - update
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - name: check delta
        run: |
          head ./cves/delta.json