---
# GitHub Action for Level 1 auditing of CVEs
# It is triggered whenever the CVE Update GitHub Action completes

name: CVE Auditor
on:
  workflow_run:
    workflows:
      - "CVE Update"
    types:
      - completed

jobs:
  audit-cves:
    name: Test Step
    environment: deployment
    runs-on: ubuntu-latest
    env:
      CVE_DELTALOG_JSON: https://raw.githubusercontent.com/CVEProject/cvelistV5/refs/heads/main/cves/deltaLog.json
      CVE_UTIL_ROOT: https://raw.githubusercontent.com/CVEProject/cvelistV5/refs/heads/main/.github/workflows/dist
      GITHUB_EVENT_CONTEXT: ${{ toJSON(github.event) }}
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 1
      - name: Setup Node to specific version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: download needed files
        run: |
          pwd
          ls -al
          mkdir -p .github/workflows/dist
          curl -L -o .github/workflows/dist/sourcemap-register.cjs ${CVE_UTIL_ROOT}/sourcemap-register.cjs
          curl -L -o .github/workflows/dist/index.mjs ${CVE_UTIL_ROOT}/index.js
          curl -L -o ./delta.json ${CVE_DELTALOG_JSON}
          ls -hal
          ls -hal .github/workflows/dist
      - name: print out some interesting environment and runtime info
        run: |
          echo "CI:  ${CI}"
          echo "GITHUB_ACTION:  ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS:  ${GITHUB_ACTIONS}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH:  ${GITHUB_EVENT_PATH}"
          echo "GITHUB_JOB:  ${GITHUB_JOB}"
          echo "GITHUB_REF_NAME:  ${GITHUB_REF_NAME}"
          echo "GITHUB_WORKFLOW:  ${GITHUB_WORKFLOW}"
          echo "github.event:  ${GITHUB_EVENT_CONTEXT}"
          echo 'delta.json head:'
          head ./delta.json
          echo 'cveUtils version:'
          node ./.github/workflows/dist/index.mjs --version
